services:
  - type: web
    name: algofin-frontend
    runtime: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./build
    autoDeploy: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
