/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "mligzafrdckazvagqeht"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1saWd6YWZyZGNrYXp2YWdxZWh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc3MzI0NDQsImV4cCI6MjA4MzMwODQ0NH0.AW36QdXBqWWkHZdVYDUTQY-sZjaqdYh524yciNgmlsA"
