import {
  createStrategyLabStrategyDefinition,
  type StrategyLabStrategyDefinition,
} from './strategyLabModels.ts';

export interface StrategyLabPineScriptResult {
  code: string;
  alertPayload: {
    route_token: string;
    strategy_id: string;
    symbol: string;
    side: '{{strategy.order.action}}' | 'buy' | 'sell';
    quantity: '{{strategy.order.contracts}}';
    price: '{{close}}';
    source: 'strategylab_pinescript';
  };
}

export function generateStrategyLabPineScript(input: {
  strategy: StrategyLabStrategyDefinition;
  routeToken: string;
  strategyId: string;
}): StrategyLabPineScriptResult {
  const strategy = createStrategyLabStrategyDefinition(input.strategy);
  const routeToken = String(input.routeToken || '').trim();
  const strategyId = String(input.strategyId || '').trim();

  if (!routeToken) {
    throw new Error('Route token is required for AlgoFin PineScript export');
  }
  if (!strategyId) {
    throw new Error('Strategy id is required for AlgoFin PineScript export');
  }

  const alertPayload = {
    route_token: routeToken,
    strategy_id: strategyId,
    symbol: strategy.symbol,
    side: '{{strategy.order.action}}' as const,
    quantity: '{{strategy.order.contracts}}' as const,
    price: '{{close}}' as const,
    source: 'strategylab_pinescript' as const,
  };
  const buyPayload = JSON.stringify({ ...alertPayload, side: 'buy' });
  const sellPayload = JSON.stringify({ ...alertPayload, side: 'sell' });
  const { indicators, risk, positionSizing } = strategy;

  return {
    alertPayload,
    code: `//@version=5
// Strategy: ${strategy.name}
// Symbol: ${strategy.symbol}
// Generated by StrategyLab for AlgoFin webhook routing
strategy("${strategy.name}", overlay=true, default_qty_type=strategy.${positionSizing.type}, default_qty_value=${positionSizing.value})

rsiLen = input.int(${indicators.rsiLength}, "RSI Length", minval=2)
emaShort = input.int(${indicators.emaShort}, "EMA Short", minval=2)
emaLong = input.int(${indicators.emaLong}, "EMA Long", minval=2)
macdFast = input.int(${indicators.macdFast}, "MACD Fast", minval=2)
macdSlow = input.int(${indicators.macdSlow}, "MACD Slow", minval=2)
macdSignal = input.int(${indicators.macdSignal}, "MACD Signal", minval=2)
slPct = input.float(${risk.stopLossPct}, "Stop Loss %", step=0.1)
tpPct = input.float(${risk.takeProfitPct}, "Take Profit %", step=0.1)
trailPct = input.float(${risk.trailingStopPct}, "Trail Stop %", step=0.1)

rsiVal = ta.rsi(close, rsiLen)
[macdLine, signalLine, _] = ta.macd(close, macdFast, macdSlow, macdSignal)
emaS = ta.ema(close, emaShort)
emaL = ta.ema(close, emaLong)

entryLong = ta.crossunder(rsiVal, 30) and ta.crossover(macdLine, signalLine) and close > emaS
exitLong = ta.crossover(rsiVal, 70) or close < emaL

if entryLong
    strategy.entry("Long", strategy.long)
    strategy.exit("Exit", "Long", stop=close * (1 - slPct / 100), limit=close * (1 + tpPct / 100), trail_offset=close * trailPct / 100)

if exitLong
    strategy.close("Long")

plot(emaS, "EMA Short", color=color.orange)
plot(emaL, "EMA Long", color=color.blue)
plotshape(entryLong, style=shape.triangleup, location=location.belowbar, color=color.green, size=size.small)
plotshape(exitLong, style=shape.triangledown, location=location.abovebar, color=color.red, size=size.small)

alertcondition(entryLong, title="BUY", message='${buyPayload}')
alertcondition(exitLong, title="SELL", message='${sellPayload}')
`,
  };
}
